In [1]:
%matplotlib inline

In [2]:
from data_loading import cifar10_flat_loader as mnist_flat
    
x_train, y_train, y_train_cls, x_test, y_test, y_test_cls, cls_names = mnist_flat.data_loading()

print(x_train.shape) 
print(y_train.shape) 
print(y_train_cls.shape) 
print(x_test.shape) 
print(y_test.shape) 
print(y_test_cls.shape)

Data has apparently already been downloaded and unpacked.
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_1
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_2
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_3
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_4
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_5
Loading data: data/CIFAR-10/cifar-10-batches-py/test_batch
Loading data: data/CIFAR-10/cifar-10-batches-py/batches.meta
(50000, 3072)
(50000, 10)
(50000,)
(10000, 3072)
(10000, 10)
(10000,)


In [3]:
import numpy as np
import tensorflow as tf
from model.softmax_regression import SoftmaxRegression
from data_loading import cifar10_flat_loader as mnist_flat
    
x_train, y_train, y_train_cls, x_test, y_test, y_test_cls, cls_names = mnist_flat.data_loading()
    
with tf.Session() as sess:
    a = SoftmaxRegression(x_train, y_train, y_train_cls, cls_names, sess,
                 lr=1e-4, epoch=100, batch_size=256, report_period=1000, np_seed=1, tf_seed=1,
                 initializer=tf.contrib.layers.variance_scaling_initializer(mode="FAN_AVG"),
                 save_path='result/model/model_1',
                 figure_save_dir='result/img')
    a.train()
        
    print('train accuracy : ', a.compute_accuracy(x_train, y_train, y_train_cls))
    print('test accuracy : ', a.compute_accuracy(x_test, y_test, y_test_cls))
    
with tf.Session() as sess:
    a = SoftmaxRegression(x_train, y_train, y_train_cls, cls_names, sess,
                 lr=1e-4, epoch=100, batch_size=256, report_period=1000, np_seed=1, tf_seed=1,
                 initializer=tf.contrib.layers.variance_scaling_initializer(mode="FAN_AVG"),
                 save_path='result/model/model_1',
                 figure_save_dir='result/img')
    a.restore()
        
    print('train accuracy : ', a.compute_accuracy(x_train, y_train, y_train_cls))
    print('test accuracy : ', a.compute_accuracy(x_test, y_test, y_test_cls))
    
    a.compute_confusion_matrix(x_test, y_test, y_test_cls)
    #a.plot_9_images_with_false_prediction(x_test, y_test, y_test_cls)

W0721 16:14:59.347293 4585244096 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



Data has apparently already been downloaded and unpacked.
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_1
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_2
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_3
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_4
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_5
Loading data: data/CIFAR-10/cifar-10-batches-py/test_batch
Loading data: data/CIFAR-10/cifar-10-batches-py/batches.meta


W0721 16:15:01.980225 4585244096 deprecation_wrapper.py:119] From /Users/sungchul/Dropbox/Git/machine_learning/logistic_regression_cifar10_flat_class_version/model/softmax_regression.py:91: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

W0721 16:15:01.980867 4585244096 deprecation_wrapper.py:119] From /Users/sungchul/Dropbox/Git/machine_learning/logistic_regression_cifar10_flat_class_version/model/softmax_regression.py:96: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0721 16:15:01.983510 4585244096 deprecation_wrapper.py:119] From /Users/sungchul/Dropbox/Git/machine_learning/logistic_regression_cifar10_flat_class_version/model/softmax_regression.py:100: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

W0721 16:15:02.014612 4585244096 deprecation_wrapper.py:119] From /Users/sungchul/Dropbox/Git/machine_learning/logistic_regression_cifar10_flat_class_version/model/

grandient_step :  1000
loss :            1.7797464

grandient_step :  2000
loss :            1.6482952

grandient_step :  3000
loss :            1.7088122

grandient_step :  4000
loss :            1.7309175

grandient_step :  5000
loss :            1.7269356

grandient_step :  6000
loss :            1.806531

grandient_step :  7000
loss :            1.8126757

grandient_step :  8000
loss :            1.5821071

grandient_step :  9000
loss :            1.773709

grandient_step :  10000
loss :            1.7686384

grandient_step :  11000
loss :            1.5861726

grandient_step :  12000
loss :            1.6308109

grandient_step :  13000
loss :            1.756038

grandient_step :  14000
loss :            1.5961334

grandient_step :  15000
loss :            1.6721687

grandient_step :  16000
loss :            1.7288929

grandient_step :  17000
loss :            1.7796974

grandient_step :  18000
loss :            1.6730354

grandient_step :  19000
loss :            1.6808386



W0721 16:16:08.464979 4585244096 deprecation_wrapper.py:119] From /Users/sungchul/Dropbox/Git/machine_learning/logistic_regression_cifar10_flat_class_version/model/softmax_regression.py:170: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

W0721 16:16:08.666783 4585244096 deprecation_wrapper.py:119] From /Users/sungchul/Dropbox/Git/machine_learning/logistic_regression_cifar10_flat_class_version/model/softmax_regression.py:158: The name tf.train.import_meta_graph is deprecated. Please use tf.compat.v1.train.import_meta_graph instead.

W0721 16:16:08.695436 4585244096 deprecation.py:323] From /Users/sungchul/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.


train accuracy :  0.43544
test accuracy :  0.4065
train accuracy :  0.43544
test accuracy :  0.4065
[[443  47  54  39  30  39  20  53 231  44]
 [ 60 498  22  33  21  45  30  57 106 128]
 [ 98  42 268  81 141 110 113  69  63  15]
 [ 37  58  94 265  71 232  82  48  57  56]
 [ 54  28 134  58 327 111 126 109  40  13]
 [ 34  46  90 157  95 378  63  66  56  15]
 [ 12  38  81 135 120 103 432  35  27  17]
 [ 40  42  56  61  96  99  38 463  58  47]
 [130  76  22  25   7  53   7  17 600  63]
 [ 77 203  19  26  21  31  42  51 139 391]]
